### ISSUE TITLE
Unable to access web interface

### ISSUE THREAD

**Issue by sanderant** [pbpraha/galactic-unicorn-trippi#1]
First let me say thanks for making this. I'm just getting started with this, but I really like light patterns.
I'm able to run your code and it seems to work, but the status doesn't load the presets and when I goto the web interface it says offline.

Below is what i see in the status.
```
Connecting to WIFI
2023-04-02 15:02:58 [debug    / 116kB]   - got ip address
Start tripping at: http://192.168.1.x
Loading Preset
```

I'm running the most current firmware if that helps.

**Comment by pbpraha** [comment]
Hi Alexander,

Thanks for you kind words :)

Regarding the problem, you wrote:

> Below is what i see in the status.
Start tripping at: http://192.168.1.x

That 'x' a the end there is confusing me somewhat because it should always be a number, never 'x'.
Question: are you simply obscuring this yourself in the comment or does the actual status contain the 'x'?

Aside from that, I did notice the following while i was developing this:
- My machine is set to use Firefox as it's default browser.
- If I click the link that Thonny displays, Firefox attempts to connect over **https**, not **http**
- The code only accepts request over **http**, not **https**
- No amount of trying would convince Firefox that it should connect over **http**

The upshot of that is that I could not use Firefox to view the UI, everything is OK when using Chrome.

Let me know if you are using Firefox and if you can connect via a different browser.

Note: I now have my GU running without Thonny and in this mode Firefox is happy to connect via **http**

**Comment by sanderant** [comment]
Hey PB,

Sorry for the confusion,  I redacted the ip address (in case anyone else was on my wifi 😄 ) but I can get to the ip address. I also had trouble with the http, but I don't think that is the problem.

I have two questions would removing the pre-installed python programs make a difference? I'm just copying the files and running them manually. I don't understand if there might still be something running from the boot before or if it might be a space issue.

Also is there a log file for the web server? I see a log.txt file, but didn't know if that was related.

Thanks,

Sander

**Comment by pbpraha** [comment]
Hi Sander,

hmm, strange results you're getting there and I'm not at all sure why it's happening.

regarding your two questions:

> would removing the pre-installed python programs make a difference?

I can't answer that unfortunately. I still have all the preinstalled stuff on my GU (plus some extra files I've been tinkering with) and haven't encountered a problem yet.

As far as I'm aware, when running a script via Thonny, no other micropython boot code runs at startup (I'm pretty new to micropython too, so don't take my word on this)

> Also is there a log file for the web server? I see a log.txt file, but didn't know if that was related.

Yes, log.txt is written for us by the wifi library - i'd like to turn off that functionality but i haven't looked into that yet.

!!! STOP THE PRESS... 
ok...
So i just did some testing, and I've noticed something rather strange...
I edited my `WIFI_CONFIG.py` that's in the root of the pico file system and _intentionally_ gave it a bad PSK (wifi password) value.
In _theory_ this means that i should not get a connection and i should not get an IP address, _but_ the output from Thonny looks correct:

![image](https://user-images.githubusercontent.com/4026146/229824197-f0cdd4f5-92a0-474c-9094-d0d3ab289300.png)

however, I am unable to reach the UI at that IP address via any browser.

I can only guess there's some error in the wifi libs that I'm using.

So, can you check and confirm that your `WIFI_CONFIG.py` file has the correct PSK value please?
From where I'm sitting it looks like this could be your error.

for the record, here's how my pico file system is set up:

![image](https://user-images.githubusercontent.com/4026146/229820769-e838a34e-daca-49a0-9557-c8e431aac23b.png)

**Comment by pbpraha** [comment]
Hi Sander,

You know what? it might help things if I actually read what you initially wrote ...

> First let me say thanks for making this. I'm just getting started with this, but I really like light patterns.
I'm able to run your code and it seems to work, but the status doesn't load the presets and when I goto the web interface it says offline.

I've just checked the code and yeah, there's a mismatch on the websocket name between the pico and the JS file.
Looks like i forgot to upload the changed script to github - very sorry for this, seems to happen more often as i get older >.<

code in the main.js file:
```const socket = new ReconnectingWebSocket(`ws://${host}/trippi`)```

code in the trippy_web_ui.py file:
```
@server.route('/tripppppy')
@with_websocket
```

as you can see, `trippi` != `tripppppy`

I'm so embarrassed.

ho hum.

I'll fix the trippy_web_ui.py file here on github, download a new copy (or change your script manually) and everything should now work.

Apologies for not spotting this sooner.

Enjoy the show :)

**Comment by test-match** [comment]
Hi,
I have the same issue despite applying the updated version. 

On launching, Thonny says:

-------------------------------------
Connecting to WIFI
2023-04-10 14:15:28 [debug    / 116kB]   - got ip address
Start tripping at: http://192.168.86.127
Loading Preset

----------------------------------------------

But unlike your example, no presets load. The web interface is faded out and shows a box with 'offline' in it. That's exactly what I see if I open the index.html file in my browser. I've tried multiple browsers (Opera, Safari, Firefox, Edge, Chrome, etc.) but none connect. I just get one trippy display, but can't change it. 

The galactic unicorn is connected to the WiFi, and I can ping it. It also runs the Pimoroni galactic paint code with no problem.

Any idea what I'm doing wrong?

Thanks

**Comment by pbpraha** [comment]
@test-match, @sanderant 

Hey Guys, 

I worked it out, it's my fault again, sorry about that.

There's an error in [trippy_web_ui/static/main.js](https://github.com/pbpraha/galactic-unicorn-trippi/blob/main/trippy_web_ui/static/main.js)

on line 9, `localdev` should have been set to `false`

when true, the code tries to connect to the hard-coded `192.168.1.11` address when it should be connecting to the same ip that the html is served from (i.e. the ip address of the GU)

i've updated the script in the repo.

let me know if this fixes the problem for you :)

pb.

**Comment by test-match** [comment]
Thanks - unfortunately that doesn't work either. 

I now see:

------------------
2023-04-10 15:44:24 [debug    / 116kB]   - got ip address
Start tripping at: http://192.168.86.127
Loading Preset
Traceback (most recent call last):
  File "/lib/microdot_asyncio.py", line 369, in dispatch_request
  File "/lib/microdot_asyncio.py", line 439, in _invoke_handler
  File "/lib/microdot_asyncio_websocket.py", line 97, in wrapper
  File "<stdin>", line 104, in echo
TypeError: can't convert NoneType to float
------------------
and the web page still shows 'offline'

Does that give you any other ideas?

**Comment by sanderant** [comment]
I think the issue is our installations don't read the presets. I haven't had the time to add in some debug statements yet to see where its failing.

I have two theories. 
The first is when you did the development you made some change to your system as part of the process we haven't, by just copying the files.
Second, long shot, is we're running a different version of the firmware which made some change. I downloaded the firmware two weeks ago, but don't recall exactly which version.

**Comment by sanderant** [comment]
I'm actually seeing the same error when I mess around a little:

```
Traceback (most recent call last):
  File "/lib/microdot_asyncio.py", line 370, in dispatch_request
  File "/lib/microdot_asyncio.py", line 443, in _invoke_handler
  File "/lib/microdot_asyncio_websocket.py", line 97, in wrapper
  File "<stdin>", line 104, in echo
TypeError: can't convert NoneType to float

```

Seems to be related to line 104:
```
        else:
            VALUES[key] = float(value)
```

When I got to the url to get that value, it is blank on my system. Can we set it manually before starting?

**Comment by pbpraha** [comment]
@sanderant @test-match 

regards:
> Seems to be related to line 104:
        else:
            VALUES[key] = float(value)

> When I got to the url to get that value, it is blank on my system. Can we set it manually before starting?

this code handles inputs from the web UI so you will not be able to go to that url, there's nothing there.

i think that one of the presets does not contain the setting, which preset is giving the trouble?

**Comment by test-match** [comment]
Thanks @pbpraha  - I'd say all the presets are the problem (sorry!). I've gradually deleted them but none seem to load. I deleted the first few one-by one, and then a few at a time until there were none left.
Incidentally, the Traceback messages I quoted above only appear when I click on the link. Nothing loads no matter how long I wait before clicking.

**Comment by sanderant** [comment]
Could it be that the initial state needs to be set and we're having trouble because the intial state is blank?

**Comment by Jfeif27** [comment]
> I'm actually seeing the same error when I mess around a little:
> 
> ```
> Traceback (most recent call last):
>   File "/lib/microdot_asyncio.py", line 370, in dispatch_request
>   File "/lib/microdot_asyncio.py", line 443, in _invoke_handler
>   File "/lib/microdot_asyncio_websocket.py", line 97, in wrapper
>   File "<stdin>", line 104, in echo
> TypeError: can't convert NoneType to float
> ```
> 
> Seems to be related to line 104:
> 
> ```
>         else:
>             VALUES[key] = float(value)
> ```
> 
> When I got to the url to get that value, it is blank on my system. Can we set it manually before starting?

I’m getting these same errors.

**Comment by Jfeif27** [comment]
Any update? I'm desperately trying to get this to work
